### ISSUE TITLE
Add country name for 'Halaska'

### ISSUE THREAD

**Issue by skykanin** [anvaka/map-of-github#10]
Add "Halaska" country name for https://anvaka.github.io/map-of-github/#10/12.1117/-8.2131

**Comment by anvaka** [comment]
Made me giggle when I saw the name - I like it :). Currently the name is given to this country by @mlochbaum as "Category of Haskell", should we rename to "Halaska"?

**Comment by anvaka** [comment]
Thank you for the suggestion!
