### ISSUE TITLE
updating new data

### ISSUE THREAD

**Issue by hoangmd2410** [anvaka/map-of-github#16]
thank you for creating such a excellent project but how often do you crawl new data from Google BigQuery to update new stars from users?

**Comment by anvaka** [comment]
I haven't decided yet. There are two ways to do it. One way is easy but ruins the existing map - basically rebuild all from scratch using the new data. The other way is to pull only new stars and augment existing countries with the data. This would preserve the mental map of countries, though clustering used by this approach might not necessary be optimal.
