### ISSUE TITLE
Sometimes search does not work.

### ISSUE THREAD

**Issue by alexey-milovidov** [anvaka/map-of-github#2]
It shows "Downloading search index for letter C" when I'm trying to search ClickHouse.
I see

```
FuzzySearch Failed to fetch index for C SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

in the console.

It tried to load https://anvaka.github.io/map-of-github-data/v1/names/C.json but GitHub returns 404.

Note: sometimes search works, for unknown reasons.

**Comment by alexey-milovidov** [comment]
Found the reason - it works only for lowercase letters:
https://github.com/anvaka/map-of-github-data/tree/main/v1/names

**Comment by anvaka** [comment]
Thank you! Looks like this will be fixed with this 

https://github.com/anvaka/map-of-github/pull/1

Will deploy it a bit later today

**Comment by anvaka** [comment]
The code is deployed, should be fixed now (or as soon as cache is invalidated locally)
