### ISSUE TITLE
Label for HPCLand

### ISSUE THREAD

**Issue by vsoch** [anvaka/map-of-github#6]
Hi! I was wondering if it's possible to suggest labels for different groups? Specifically here: 
![image](https://github.com/anvaka/map-of-github/assets/814322/8525f264-72c1-4f45-aa47-225afdd499dc)
 
https://anvaka.github.io/map-of-github/#10.85/33.6947/21.6164

These are package managers / job orchestration / containers for High Performance Computing, so I'm wondering if we can call it HPCLand.

Thank you for making this it's so beautiful I love it! <3

**Comment by anvaka** [comment]
Thank you! Should be deployed shortly

**Comment by vsoch** [comment]
Awesome! Thank you so much!
